language: node_js
node_js: 
  - 13

services:
  - docker

# Test installation
install:
  - echo "nothing need to be test"

# executed scrip
before_script:
  - echo "no test"

script:
  - docker --version # print the version for logging
  # Build images
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  # prepare for update image on docker hub
  - docker tag udagram-reverseproxy kevin6kone/udagram-reverseproxy:v3
  - docker tag udagram-api-user kevin6kone/udagram-api-user:v3
  - docker tag udagram-api-feed kevin6kone/udagram-api-feed:v3
  - docker tag udagram-frontend kevin6kone/udagram-frontend:v3

# task must be execute after process run successfully
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kevin6kone/udagram-reverseproxy:v3
  - docker push kevin6kone/udagram-api-user:v3
  - docker push kevin6kone/udagram-api-feed:v3
  - docker push kevin6kone/udagram-frontend:v3