apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  labels:
    app: feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
      - name: udagram-api-feed
        image: kevin6kone/udagram-api-feed:v2
        ports:
        - containerPort: 80

